[package]
name = "theta_star_bi_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "theta_star_bi_rust"
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.33.0"
pyo3 = "0.22.0"
